import React, { useState, useEffect } from 'react';
import { Text, Box, Newline } from 'ink';
import { ClaudeAnalysisResult, ClaudeProject } from '../types/index.js';

interface SummaryDashboardProps {
  analysisResult: ClaudeAnalysisResult;
  targetDate: string;
}

const SummaryDashboard: React.FC<SummaryDashboardProps> = ({
  analysisResult,
  targetDate,
}) => {
  const [currentTime, setCurrentTime] = useState(new Date());

  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentTime(new Date());
    }, 1000);

    return () => clearInterval(timer);
  }, []);

  const formatDate = (date: string) => {
    return new Date(date).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      weekday: 'long',
    });
  };

  const getMostActiveProject = (): ClaudeProject | null => {
    if (analysisResult.projects.length === 0) return null;
    return analysisResult.projects.reduce((max, project) =>
      project.totalMessages > max.totalMessages ? project : max
    );
  };

  const mostActiveProject = getMostActiveProject();

  return (
    <Box flexDirection="column" padding={1}>
      {/* Header */}
      <Box>
        <Text color="cyan" bold>
          📊 Claude Code Summary Dashboard
        </Text>
      </Box>
      <Box>
        <Text color="gray">
          Current Time: {currentTime.toLocaleTimeString('en-US')}
        </Text>
      </Box>
      <Newline />

      {/* Date Info */}
      <Box>
        <Text color="yellow" bold>
          📅 Target Date: {formatDate(targetDate)}
        </Text>
      </Box>
      <Newline />

      {/* Main Stats */}
      <Box flexDirection="column" borderStyle="round" borderColor="blue" paddingX={2}>
        <Text color="blue" bold>
          🎯 Basic Statistics
        </Text>
        <Box justifyContent="space-between">
          <Text>Projects:</Text>
          <Text color="green" bold>
            {analysisResult.projects.length}
          </Text>
        </Box>
        <Box justifyContent="space-between">
          <Text>Sessions:</Text>
          <Text color="green" bold>
            {analysisResult.totalSessions}
          </Text>
        </Box>
        <Box justifyContent="space-between">
          <Text>Messages:</Text>
          <Text color="green" bold>
            {analysisResult.totalMessages}
          </Text>
        </Box>
      </Box>
      <Newline />

      {/* Most Active Project */}
      {mostActiveProject && (
        <>
          <Box flexDirection="column" borderStyle="round" borderColor="green" paddingX={2}>
            <Text color="green" bold>
              🚀 Most Active Project
            </Text>
            <Box justifyContent="space-between">
              <Text>Project Name:</Text>
              <Text color="cyan" bold>
                {mostActiveProject.name}
              </Text>
            </Box>
            <Box justifyContent="space-between">
              <Text>Messages:</Text>
              <Text color="green" bold>
                {mostActiveProject.totalMessages}
              </Text>
            </Box>
            <Box justifyContent="space-between">
              <Text>Sessions:</Text>
              <Text color="green" bold>
                {mostActiveProject.totalSessions}
              </Text>
            </Box>
          </Box>
          <Newline />
        </>
      )}

      {/* Project List */}
      <Box flexDirection="column" borderStyle="round" borderColor="magenta" paddingX={2}>
        <Text color="magenta" bold>
          📁 Project List
        </Text>
        {analysisResult.projects.map((project, index) => (
          <Box key={project.path} justifyContent="space-between">
            <Text>
              {index + 1}. {project.name}
            </Text>
            <Text color="gray">
              {project.totalMessages}msg / {project.totalSessions}sess
            </Text>
          </Box>
        ))}
        {analysisResult.projects.length === 0 && (
          <Text color="gray">No activity on this day</Text>
        )}
      </Box>
      <Newline />

      {/* Footer */}
      <Box justifyContent="center">
        <Text color="gray" italic>
          🤖 Generated by ccsummary - Press Ctrl+C to exit
        </Text>
      </Box>
    </Box>
  );
};

export default SummaryDashboard;